# Generated by Django 6.0.7 on 2026-08-09 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('autor_nombre', models.CharField(max_length=150)),
                ('ciclo', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='Ciclo')),
                ('estado_publicacion', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='carreras.carrera', verbose_name='Carrera')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.categoria')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ods_id', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ODS del Proyecto',
                'verbose_name_plural': 'ODS del Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto3D',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.proyecto')),
                ('archivo_fbx', models.FileField(upload_to='modelos_3d/fbx/')),
                ('imagen_miniatura', models.ImageField(blank=True, null=True, upload_to='portadas/3d/')),
                ('configuracion_interactiva', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Proyecto 3D',
                'verbose_name_plural': 'Proyectos 3D',
            },
            bases=('proyectos.proyecto',),
        ),
        migrations.CreateModel(
            name='ProyectoSoftware',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.proyecto')),
                ('archivo_video', models.FileField(blank=True, null=True, upload_to='videos_software/')),
                ('url_repositorio', models.URLField(blank=True, null=True)),
                ('url_demo_live', models.URLField(blank=True, null=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/software/')),
            ],
            options={
                'verbose_name': 'Proyecto de Software',
                'verbose_name_plural': 'Proyectos de Software',
            },
            bases=('proyectos.proyecto',),
        ),
    ]
