# Generated by Django 6.0.7 on 2026-08-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyectoods',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ods_relacionados', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='proyectosoftware',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='proyectos_software', to='proyectos.tecnologia'),
        ),
        migrations.AlterUniqueTogether(
            name='proyectoods',
            unique_together={('proyecto', 'ods_id')},
        ),
    ]
