# Generated by Django 6.0.7 on 2026-08-09 23:49

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('3D', 'Proyecto 3D'), ('SOFTWARE', 'Proyecto de Software')], max_length=10)),
                ('autor_nombre', models.CharField(max_length=150)),
                ('token', models.CharField(default=invitaciones.models.generar_token, editable=False, max_length=64, unique=True)),
                ('expira_en', models.DateTimeField(default=invitaciones.models.calcular_expiracion)),
                ('usado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invitación de proyecto',
                'verbose_name_plural': 'Invitaciones de proyecto',
                'ordering': ['-created_at'],
            },
        ),
    ]
