# Generated by Django 6.0.7 on 2026-08-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistas_totales', models.PositiveIntegerField(default=0)),
                ('likes_totales', models.PositiveIntegerField(default=0)),
                ('compartidos_totales', models.PositiveIntegerField(default=0)),
                ('ultima_visita', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
